[package]
name = "acto"
version = "0.2.0"
authors = ["Roland Kuhn <rk@rkuhn.info>"]
edition = "2021"
description = "light-weight Actor library for Rust"
repository = "https://github.com/rkuhn/acto"
documentation = "https://docs.rs/acto"
license = "Apache-2.0 OR MIT"
keywords = ["actors", "concurrency"]
categories = ["concurrency"]

[features]
with_async-std = ["async-std"]
with_tokio = ["tokio"]

[dependencies]
async-std = { version = "1", optional = true, features = ["attributes"] }
futures = { version = "0.3" }
parking_lot = "0.12"
tokio = { version = "1", optional = true }

[dev-dependencies]
futures = { version = "0.3", features = ["executor"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
