[package]
name = "acto"
version = "0.2.0"
authors = ["Roland Kuhn <rk@rkuhn.info>"]
edition = "2018"
description = "light-weight Actor library for Rust"
repository = "https://github.com/Actyx/acto"
documentation = "https://docs.rs/acto"
license = "Apache-2.0 OR MIT"
keywords = ["actors", "concurrency"]
categories = ["concurrency"]

[dependencies]
anyhow = "1.0.40"
derive_more = "0.99.11"
futures = "0.3.14"
parking_lot = "0.11.1"
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread", "sync"] }
tokio-stream = "0.1.5"
