[package]
name = "acto"
version = "0.2.0"
authors = ["Roland Kuhn <rk@rkuhn.info>"]
edition = "2018"
description = "light-weight Actor library for Rust"
repository = "https://github.com/Actyx/acto"
documentation = "https://docs.rs/acto"
license = "Apache-2.0 OR MIT"
keywords = ["actors", "concurrency"]
categories = ["concurrency"]

[features]
with_async-std = ["async-std"]
with_tokio = ["tokio"]
with_futures = ["futures"]

[dependencies]
anyhow = "1.0.40"
async-std = { version = "1.9.0", optional = true, features = ["attributes"] }
derive_more = "0.99.11"
futures = { version = "0.3.14", optional = true }
parking_lot = "0.11.1"
tokio = { version = "1", optional = true, features = ["rt", "macros", "rt-multi-thread", "sync"] }

[dev-dependencies]
futures = { version = "0.3.14", features = ["executor"] }
